### ISSUE TITLE
Links to technical summary ePub and PDF are broken.

### ISSUE THREAD

**Issue by CameronBanga** [apple/VideoFlashingReduction#1]
Just a heads up, seeing an error when linking:

https://developer.apple.com/accessibility/downloads/Video-Flashing-Reduction-12.pdf

https://developer.apple.com/accessibility/downloads/Video-Flashing-Reduction-12.epub

Both land on a "The page you’re looking for can’t be found" page.

**Comment by cookiecrook** [comment]
Thanks @CameronBanga for pointing this out, and to @eduaranega for getting it fixed!
