### ISSUE TITLE
Flaw of algorithm recognized by person with photosensitive epilepsy and proposition of possible improvement

### ISSUE THREAD

**Issue by neuryt** [apple/VideoFlashingReduction#2]
Hello! 
First, some background from my side. I am software QA with a bit of knowledge about signal processing who happens to be epileptic and photosensitive.

I tested iphone implementation of this algorithm and it is like wonder - I will be way safer. However during testing I noticed one issue. It isn't catching videos where global luminancy and contrast are constant and parts of screen are blinking (probably - that was "calculated by my eye", should be verified by somebody without epilepsy), like this some parts of this video: (oblivious trigger warning) https://youtu.be/faCG8cmgRP8 

I checked it with safety measurments, (very small  player several metres from me - I was safe) but I recognized few parts that used to trigger my brain. For example that part with "you deserve seizure" text with rotating blinking colours. 

So, checking only global contrast and luminancy is in my opinion flaw of this algorithm. I think that it can be easy to improve by checking quarters of screen and full screen for example, to avoid false negative situations like one described above. I known that it would require much more computing power - but impact is IMHO (biased) opinion worth it.

Can somebody who can check this safety confirm my thoughts? I would be really happy to be even safer - but current implementation is already real wonder.

**Comment by andrewbwatson** [comment]
Hi Neuryt,
Thanks for your interest in this feature, and your thoughtful comment. You are correct that the current algorithm is based on the average luminance of each frame. The precise stimulus for discomfort is complex and still a subject of research, so we have chosen to first handle the largest and most certain stimulus which is the average luminance. We are aware of issues regarding the distribution of luminance over space and time, and will continue to study these and other aspects of video induced discomfort.
