### ISSUE TITLE
"Dim Flashing Lights" setting not available on iPad Pro 10.5"

### ISSUE THREAD

**Issue by mg8973** [apple/VideoFlashingReduction#3]
The Apple Developer site states that the "Dim Flashing Lights" feature is available on all devices running iOS or iPadOS 16.4 and above. However after updating to iPadOS 16.6.1, this feature does not show up in Settings.
![IMG_0385](https://github.com/apple/VideoFlashingReduction/assets/52803804/aa632a75-b2f4-4f2e-9e55-49b7d8b08258)

**Comment by eduaranega** [comment]
Thank you for your question! Dim Flashing Lights is not supported on this particular model of iPad Pro.

**Comment by mg8973** [comment]
@eduaranega Thank you for letting me know!

**Comment by cookiecrook** [comment]
For future reference, Apple Feedback Assistant is the preferred path for that type of report. This GitHub issue tracker should be used for problems or improvements for the algorithm or any of its documentation here. Thanks.
